apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-app
    kubernetes.io/instance: kafka
  annotations:
    meta.helm.sh/release-name: kafka
  name: {{ .Values.service.name }}
spec:
  ports:
{{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      protocol: TCP
      targetPort: {{ .targetPort }}
{{- end }}
  selector:
    app: kafka-app